import sqlite3
import os
import json
import sys

def generate_dsl(db_path, board_id, output_path):
    print(f"[Aether Generator] Compiling DSL for board '{board_id}'...")
    if not os.path.exists(db_path):
        print(f"[Aether Generator] Error: DB file not found at {db_path}", file=sys.stderr)
        return False
        
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    try:
        conn.execute("PRAGMA journal_mode=WAL;")
        conn.execute("PRAGMA busy_timeout = 5000;")
        cursor = conn.cursor()
        
        # 1. ノード（付箋、トピック、要約、コード、事実など）の取得
        cursor.execute(
            "SELECT * FROM nodes WHERE board_id = ? ORDER BY sort_order ASC;",
            (board_id,)
        )
        nodes_rows = cursor.fetchall()
        
        # 2. 接続線の取得
        cursor.execute(
            "SELECT * FROM relations WHERE board_id = ? ORDER BY sort_order ASC;",
            (board_id,)
        )
        relations_rows = cursor.fetchall()
        
        dsl_lines = []
        dsl_lines.append(f"# Aether DSL Generated for Board: {board_id}")
        dsl_lines.append("# Generated by Eleanor's Aether Generator")
        dsl_lines.append("")
        
        # カテゴリ分け用のバッファ
        stickies = []
        callouts = []
        paths = []
        drawings = []
        
        for row in nodes_rows:
            ntype = row["type"]
            if ntype in ("drawing", "circle-area", "icon"):
                drawings.append(row)
            elif ntype == "callout":
                callouts.append(row)
            elif ntype == "path":
                paths.append(row)
            else:
                # sticky として出力（summary, topic, fact, code も見た目は sticky）
                stickies.append(row)
                
        # ---------------------------------------------------------
        # A. Stickies の出力
        # ---------------------------------------------------------
        dsl_lines.append("# === STICKIES ===")
        for row in stickies:
            sid = row["id"]
            title = row["title"]
            desc = row["desc"]
            pos_x = row["pos_x"]
            pos_y = row["pos_y"]
            color = row["color"]
            role = row["role"]
            confidence = row["confidence"]
            time_step = row["time"]
            tone = row["tone"]
            properties_str = row["properties"]
            
            # JSON拡張プロパティのパース
            props = {}
            if properties_str:
                try:
                    props = json.loads(properties_str)
                except ValueError:
                    pass
            
            # タグは properties.tags のみ（color を誤用しない）
            tags = props.get("tags", "") or ""
                
            dsl_lines.append(f'sticky {sid} "{title}" {{')
            if pos_x is not None and pos_y is not None:
                dsl_lines.append(f"  pos: {int(pos_x)} {int(pos_y)}")
            if color:
                dsl_lines.append(f'  color: "{color}"')
            if tags:
                dsl_lines.append(f'  tags: "{tags}"')
            if role:
                dsl_lines.append(f'  role: "{role}"')
            if confidence:
                # 数値型か文字列型かで出し分け
                try:
                    conf_float = float(confidence)
                    dsl_lines.append(f"  confidence: {conf_float}")
                except ValueError:
                    dsl_lines.append(f'  confidence: "{confidence}"')
            if time_step:
                dsl_lines.append(f'  time: "{time_step}"')
            if tone:
                dsl_lines.append(f'  tone: "{tone}"')
                
            # desc 内の改行は \n にエスケープする
            if desc:
                escaped_desc = desc.replace("\n", "\\n")
                dsl_lines.append(f'  desc: "{escaped_desc}"')
                
            # その他拡張プロパティの出力
            for k, v in props.items():
                if k not in ("tags", "desc", "pos_x", "pos_y", "color", "role", "confidence", "time", "tone"):
                    if isinstance(v, (int, float)):
                        dsl_lines.append(f"  {k}: {v}")
                    else:
                        dsl_lines.append(f'  {k}: "{v}"')
                        
            dsl_lines.append("}")
            dsl_lines.append("")
            
        # ---------------------------------------------------------
        # B. Callouts の出力
        # ---------------------------------------------------------
        if callouts:
            dsl_lines.append("# === CALLOUTS ===")
            for row in callouts:
                cid = row["id"]
                title = row["title"]
                properties_str = row["properties"]
                
                props = {}
                if properties_str:
                    try:
                        props = json.loads(properties_str)
                    except ValueError:
                        pass
                
                anchor = props.get("anchor", "")
                offset_x = props.get("offset_x", 0)
                offset_y = props.get("offset_y", 0)
                color = row["color"] or props.get("color", "")
                tags = props.get("tags", "")
                time_step = row["time"] or props.get("time", "")
                
                dsl_lines.append(f'callout {cid} "{title}" {{')
                if anchor:
                    dsl_lines.append(f'  anchor: "{anchor}"')
                dsl_lines.append(f"  offset: {int(offset_x)} {int(offset_y)}")
                if color:
                    dsl_lines.append(f'  color: "{color}"')
                if tags:
                    dsl_lines.append(f'  tags: "{tags}"')
                if time_step:
                    dsl_lines.append(f'  time: "{time_step}"')
                dsl_lines.append("}")
                dsl_lines.append("")
                
        # ---------------------------------------------------------
        # C. Paths の出力
        # ---------------------------------------------------------
        if paths:
            dsl_lines.append("# === PATHS ===")
            for row in paths:
                pid = row["id"]
                label = row["title"]
                properties_str = row["properties"]
                
                props = {}
                if properties_str:
                    try:
                        props = json.loads(properties_str)
                    except ValueError:
                        pass
                        
                nodes_list = props.get("nodes", "")
                style = props.get("style", "pulse")
                color = row["color"] or props.get("color", "")
                tags = props.get("tags", "")
                time_step = row["time"] or props.get("time", "")
                
                dsl_lines.append(f'path {pid} "{label}" {{')
                if nodes_list:
                    dsl_lines.append(f'  nodes: "{nodes_list}"')
                if style:
                    dsl_lines.append(f'  style: "{style}"')
                if color:
                    dsl_lines.append(f'  color: "{color}"')
                if tags:
                    dsl_lines.append(f'  tags: "{tags}"')
                if time_step:
                    dsl_lines.append(f'  time: "{time_step}"')
                dsl_lines.append("}")
                dsl_lines.append("")
                
        # ---------------------------------------------------------
        # D. Drawings (領域/アイコン) の出力
        # ---------------------------------------------------------
        if drawings:
            dsl_lines.append("# === DRAWINGS ===")
            for row in drawings:
                did = row["id"]
                title = row["title"]
                dtype = row["type"] # 'circle-area', 'icon', etc.
                pos_x = row["pos_x"]
                pos_y = row["pos_y"]
                color = row["color"]
                time_step = row["time"]
                properties_str = row["properties"]
                
                props = {}
                if properties_str:
                    try:
                        props = json.loads(properties_str)
                    except ValueError:
                        pass
                
                # drawings 特有の属性
                draw_type = props.get("type", dtype) # fallback
                style = props.get("style", "")
                targets = props.get("targets", "")
                anchor = props.get("anchor", "")
                offset_x = props.get("offset_x", 0)
                offset_y = props.get("offset_y", 0)
                tags = props.get("tags", "")
                
                dsl_lines.append(f'drawing {did} "{title}" {{')
                if draw_type:
                    dsl_lines.append(f'  type: "{draw_type}"')
                if style:
                    dsl_lines.append(f'  style: "{style}"')
                if targets:
                    dsl_lines.append(f'  targets: "{targets}"')
                if anchor:
                    dsl_lines.append(f'  anchor: "{anchor}"')
                if pos_x is not None and pos_y is not None:
                    dsl_lines.append(f"  pos: {int(pos_x)} {int(pos_y)}")
                if offset_x is not None and offset_y is not None and (offset_x != 0 or offset_y != 0):
                    dsl_lines.append(f"  offset: {int(offset_x)} {int(offset_y)}")
                if color:
                    dsl_lines.append(f'  color: "{color}"')
                if tags:
                    dsl_lines.append(f'  tags: "{tags}"')
                if time_step:
                    dsl_lines.append(f'  time: "{time_step}"')
                dsl_lines.append("}")
                dsl_lines.append("")
                
        # ---------------------------------------------------------
        # E. Relations の出力
        # ---------------------------------------------------------
        if relations_rows:
            dsl_lines.append("# === RELATIONS ===")
            for row in relations_rows:
                rid = row["id"]
                from_id = row["from_id"]
                to_id = row["to_id"]
                rtype = row["type"]
                label = row["label"]
                color = row["color"]
                weight = row["weight"]
                flow = row["flow"]
                time_step = row["time"]
                
                # 特殊な属性がないシンプルな接続線の場合
                if (not rid or rid.startswith("auto_")) and not rtype and not label and not color and not weight and not flow and not time_step:
                    dsl_lines.append(f"{from_id} -> {to_id}")
                else:
                    # idが自動生成（auto_等）の場合は出さないこともあるが、一意に特定するために定義ブロックとする
                    rel_id_part = f" {rid}" if rid and not rid.startswith("auto_") else ""
                    dsl_lines.append(f"relation{rel_id_part} {from_id} -> {to_id} {{")
                    if rtype and rtype != 'default':
                        dsl_lines.append(f'  type: "{rtype}"')
                    if label:
                        dsl_lines.append(f'  label: "{label}"')
                    if color:
                        dsl_lines.append(f'  color: "{color}"')
                    if weight and weight != 1:
                        dsl_lines.append(f"  weight: {weight}")
                    if flow:
                        dsl_lines.append(f'  flow: "{flow}"')
                    if time_step:
                        dsl_lines.append(f'  time: "{time_step}"')
                    dsl_lines.append("}")
                dsl_lines.append("")
                
        # ファイル出力
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(dsl_lines))
            
        print(f"[Aether Generator] Compilation successful. Written to {output_path}")
        return True
        
    except Exception as e:
        print(f"[Aether Generator] Compile error: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        return False
    finally:
        conn.close()

if __name__ == "__main__":
    current_dir = os.path.dirname(os.path.abspath(__file__))
    db_path = os.path.join(current_dir, "aether.db")
    # テスト用出力先
    output_path = os.path.join(os.path.dirname(current_dir), "aether_dsl_test.txt")
    generate_dsl(db_path, "succession_navi", output_path)
